# a = input("enter your name:")
# print("my name is",a)
x = input("enter first number:")
y = input("enter second number:")

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x // y)
print(x % y)

# print("printing with")
# print(int(x)+int(y))
# print(int(x)-int(y))
# print(int(x)*int(y))
# print(int(x)/int(y))
# print(int(x)//int(y))
# print(int(x)%int(y))
